title: <p align="center"> Jeevitha Ravi </p>
logo: /assets/img/mypic.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/jeevitha-ravi">LinkedIn</a> |
  <a href="https://github.com/jravi97">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>
theme: jekyll-theme-minimal
